server_config:
  api_host: "0.0.0.0:3000"
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 120s
  shutdown_timeout: 15s

transport:
  dial_timeout: 5s
  response_header_timeout: 10s
  keep_alive: 30s
  max_idle_conns_per_host: 100

router_config:
  services:
    user-service: "http://localhost:8081"

  routes:
    - prefix: "/user"
      service: "user-service"
      methods:
        - GET
